### PR TITLE
Add ppc64le build

### PR DESCRIPTION
**Pull request by sdebionne**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sdebionne** [comment]
@conda-forge-admin, please rerender

**Comment by sdebionne** [comment]
@tschoonj Well, it looks like building is not enough to get the package uploaded to [Anaconda](https://anaconda.org/conda-forge/hdf5plugin). Looking at the [conda-forge.yml doc](https://conda-forge.org/docs/maintainer/conda_forge_yml.html), I cannot find anything related to the upload. Any ideas?

**Comment by tschoonj** [comment]
I opened #18, switching to azure for the ppc64le builds. Travis is shit nowadays.

**Comment by tschoonj** [comment]
Done, the ppc64le packages have been created now. I recommend you use azure explicitly when adding support for ppc64le.

**Pull request merged**
