### PR TITLE
Rebuild for hdf5 1.12.1

### PR DESCRIPTION
**Pull request by Anthchirp**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

This also disables Python 3.6 builds

h5py follows NEP-29 and has dropped Python 3.6 support in Oct 2020,
h5py/h5py@0748060, associated PR with more info: https://github.com/h5py/h5py/pull/1727

The conda-forge h5py package does not build on Python 3.6 any more,
conda-forge/h5py-feedstock@70b5c7d

therefore there is no Python 3.6 h5py build for HDF5 1.12.

The solution therefore is to drop Python 3.6 builds downstream, too.
If there has to be a future Python 3.6 build of hdf5plugin then that
may have to go into a feedstock branch.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
Not sure why the `linux_ppc64le_python3.9.____cpython` build fails with
```
Failed to load filter blosc: /home/conda/feedstock_root/build_artifacts/hdf5plugin_1632846866921/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/hdf5plugin/plugins/libh5blosc.so
.E......
======================================================================
ERROR: testBlosc (hdf5plugin.test.TestHDF5PluginRW)
Write/read test with blosc filter plugin
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/hdf5plugin_1632846866921/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/hdf5plugin/test.py", line 116, in testBlosc
    self._test('blosc')  # Default options
  File "/home/conda/feedstock_root/build_artifacts/hdf5plugin_1632846866921/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/hdf5plugin/test.py", line 72, in _test
    f.create_dataset("data", data=data, chunks=data.shape, **args)
  File "/home/conda/feedstock_root/build_artifacts/hdf5plugin_1632846866921/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/h5py/_hl/group.py", line 149, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/home/conda/feedstock_root/build_artifacts/hdf5plugin_1632846866921/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 107, in make_new_dset
    dcpl = filters.fill_dcpl(
  File "/home/conda/feedstock_root/build_artifacts/hdf5plugin_1632846866921/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/h5py/_hl/filters.py", line 281, in fill_dcpl
    raise ValueError("Unknown compression filter number: %s" % compression)
ValueError: Unknown compression filter number: 32001

```

**Comment by t20100** [comment]
Looks weird: Other filters work fine, other versions of python also..

**Comment by Anthchirp** [comment]
Resolved in #31

**Pull request closed without merging**
